# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: 18aa82dcb10c533e5a368dc0fc253a4ef293f354b8fd5136f591c8a3ac37e65abfdfb841f78f78962f3ef611068901b5be5ea6b73571a251277b42386367e735
  

test:
  secret_key_base: eccb06065f48959eb22f36ce7eb47159531a24e9e0e87a8f231f811099a21bfbaf578915438c2ce7a0c627db8137794751231fc6f3687a0dab3aa4bfca2f47ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>

# Securing the Secrets File

# Some developers take steps to prevent the config/secrets.yml file from being checked into Git. To prevent the file # from being saved to your repo you could add the filename to the .gitignore file in your application root directory.
# If you’ve used Unix environment variables in the config/secrets.yml file, there’s no reason to add the file
# to .gitignore. If you only reveal the SECRET_KEY_BASE used for development or testing, and no one can access 
# your development machine, no useful secrets will be revealed in your GitHub repo.
# When you deploy to Heroku, the config/secrets.yml file must be in your Git repository. For that reason, I suggest
# you save the file in your Git repo and keep your secrets safe by using environment variables.  
# Pour protéger l secret key Base rajouter la variable dans le fichier .bashrc 
# ou .bash_profile et décommenter la ligne ci-dessous
# secret_key_base: very_long_random_string
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
